### ISSUE TITLE
Failed to read apiboot.txt

### ISSUE THREAD

**Issue by bglad** [AughtNaughtZero/weather_word#3]
Not exactly sure why its failed to read. Is this another directory problem?

**Comment by bglad** [comment]
Perhaps, I can just skip apiboot.txt all together. So instead of apiUrl = "http://api.wunderground.com/api/" + str(apiVal[0]) + "/hourly/q/" + str(apiVal[1]) + ".json", Just give it apiURL = "http://api.wunderground.com/api/myAPI/hourly/q/CA/San_Francisco.json"

**Comment by AughtNaughtZero** [comment]
To keep your project going, I believe that your solution would work. The apiboot.txt was intended to be an easier method of setup so that the code would not need to be edited directly in order for it to work. I thought that I had trailed all of the queries but maybe I missed this one. Did you put // between the state and city or just / ?

**Comment by AughtNaughtZero** [comment]
Also, yes, the directory matters ... The apiboot.txt file should be located at /home/pi/weather_word
